name: ChristmasGifts
version: '1.4'
main: ru.mitriyf.christmasgifts.ChristmasGifts
authors: [ JDevs, Mitriyf ]
api-version: 1.13
softdepend: [ DecentHolograms, HolographicDisplays, FancyHolograms, PlaceholderAPI, WorldGuard, WorldEdit ]
commands:
  christmasgifts:
    aliases: [ gifts ]